[package]
name = "brilift"
version = "0.1.0"
edition = "2021"

[dependencies]
bril-rs = { path = "../bril-rs", features = [
    "memory",
    "float",
    "ssa",
    "speculate",
    "position",
    "import",
    "char",
] }
bril2json = { path = "../bril-rs/bril2json" }
cranelift-codegen = { version = "0.106.0", features = ["all-arch"] }
cranelift-frontend = "0.106.0"
cranelift-object = "0.106.0"
cranelift-module = "0.106.0"
cranelift-native = "0.106.0"
cranelift-jit = "0.106.0"
argh = "^0.1.12"
simplelog = "^0.12.2"
enum-map = "^2.7.3"
